---
unclassified:
  location:
    url: http://localhost/jenkins
jenkins:
  systemMessage: "Jenkins for NodeJS App."
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
jobs:
  - script: >
      freeStyleJob("Seed Job") {
        scm {
          github('umairadeeb/nodejs-helloworld', 'master')
        }
        steps {
          dsl {
            external('jenkins/jobs/*.groovy')
          }
        }
      }