apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins_nodejs
          name: jenkins
          imagePullPolicy: Never
          env:
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "admin"
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
            - name: JENKINS_OPTS
              value: "--prefix=/jenkins"
            - name: CASC_JENKINS_CONFIG
              value: "/usr/share/jenkins/ref/"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 30005
      targetPort: 30005
      nodePort: 30005
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
spec:
  rules:
    - http:
        paths:
          - path: /jenkins
            backend:
              serviceName: jenkins
              servicePort: 8080

