apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins_nodejs
          name: jenkins
          imagePullPolicy: Never
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_DB
              value: "nodejs_helloworld"
            - name: MYSQL_USER
              value: "nodejs"
            - name: MYSQL_PASS
              value: "nodejs_helloworld"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: jenkins

